language: android
jdk: oraclejdk8
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ANDROID_API_LEVEL=23

    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
      - tools # to install Android SDK tools 25.1.x
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL

    - addon-google_apis-google-$ANDROID_API_LEVEL

    - extra-google-google_play_services

    - extra-android-support

    - extra-google-m2repository
    - extra-android-m2repository


script:
  - ./gradlew clean check connectedCheck -x library:signArchives -PdisablePreDex
